# Generated by Django 5.0.3 on 2024-03-22 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PredictionApp', '0002_userprofile_plant_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='user',
        ),
    ]
