# Generated by Django 5.0.3 on 2024-03-24 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PredictionApp', '0006_plant_user_alter_plant_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantanalytics',
            name='plant',
        ),
        migrations.AddField(
            model_name='plantanalytics',
            name='plant_photo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='PredictionApp.plantphoto'),
        ),
    ]
