# Generated by Django 5.0.3 on 2024-03-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PredictionApp', '0007_remove_plantanalytics_plant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantanalytics',
            name='greenhouse_humidity',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plantanalytics',
            name='greenhouse_illumination',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plantanalytics',
            name='greenhouse_temprature',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plantanalytics',
            name='plant_supply_K',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plantanalytics',
            name='plant_supply_N',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plantanalytics',
            name='plant_supply_P',
            field=models.TextField(blank=True),
        ),
    ]
