# Generated by Django 5.0.3 on 2024-03-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PredictionApp', '0009_remove_plantanalytics_greenhouse_humidity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantanalytics',
            name='plant_photo_processed',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='plantanalytics',
            name='disease_degree',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='plantanalytics',
            name='disease_degree_description',
            field=models.TextField(blank=True),
        ),
    ]
