# Generated by Django 5.0.3 on 2024-04-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PredictionApp', '0011_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='preview_image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
