# Generated by Django 5.0.3 on 2024-04-07 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PredictionApp', '0012_alter_plant_preview_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantphoto',
            name='date_taken',
        ),
        migrations.RemoveField(
            model_name='plantphoto',
            name='greenhouse_humidity',
        ),
        migrations.RemoveField(
            model_name='plantphoto',
            name='greenhouse_illumination',
        ),
        migrations.RemoveField(
            model_name='plantphoto',
            name='greenhouse_temprature',
        ),
        migrations.RemoveField(
            model_name='plantphoto',
            name='plant',
        ),
        migrations.RemoveField(
            model_name='plantphoto',
            name='plant_supply_K',
        ),
        migrations.RemoveField(
            model_name='plantphoto',
            name='plant_supply_N',
        ),
        migrations.RemoveField(
            model_name='plantphoto',
            name='plant_supply_P',
        ),
        migrations.CreateModel(
            name='ArchiveNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateField()),
                ('greenhouse_temprature', models.TextField(blank=True)),
                ('greenhouse_humidity', models.TextField(blank=True)),
                ('greenhouse_illumination', models.TextField(blank=True)),
                ('plant_supply_N', models.TextField(blank=True)),
                ('plant_supply_P', models.TextField(blank=True)),
                ('plant_supply_K', models.TextField(blank=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='PredictionApp.plant')),
            ],
        ),
        migrations.AddField(
            model_name='plantphoto',
            name='plant_photo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='PredictionApp.archivenote'),
        ),
    ]
