# Generated by Django 5.0.3 on 2024-04-09 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PredictionApp', '0015_rename_archivenote_photo_plantphoto_archivenote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantphoto',
            name='archiveNote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='PredictionApp.archivenote'),
        ),
    ]
