# Generated by Django 5.0.3 on 2024-03-22 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(max_length=100)),
                ('identifier', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('preview_image', models.ImageField(upload_to='plant_previews/')),
                ('planting_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PlantPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='plant_photos/')),
                ('date_taken', models.DateField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='PredictionApp.plant')),
            ],
        ),
    ]
