# Generated by Django 5.0.3 on 2024-03-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PredictionApp', '0004_remove_plant_planting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='planting_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
