# Generated by Django 5.0.3 on 2024-03-24 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PredictionApp', '0005_plant_planting_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plant',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='preview_image',
            field=models.ImageField(blank=True, upload_to='plant_previews/'),
        ),
        migrations.CreateModel(
            name='PlantAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_degree', models.IntegerField()),
                ('disease_degree_description', models.TextField()),
                ('plant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='PredictionApp.plant')),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
