# Generated by Django 5.0.3 on 2024-03-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PredictionApp', '0008_plantanalytics_greenhouse_humidity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantanalytics',
            name='greenhouse_humidity',
        ),
        migrations.RemoveField(
            model_name='plantanalytics',
            name='greenhouse_illumination',
        ),
        migrations.RemoveField(
            model_name='plantanalytics',
            name='greenhouse_temprature',
        ),
        migrations.RemoveField(
            model_name='plantanalytics',
            name='plant_supply_K',
        ),
        migrations.RemoveField(
            model_name='plantanalytics',
            name='plant_supply_N',
        ),
        migrations.RemoveField(
            model_name='plantanalytics',
            name='plant_supply_P',
        ),
        migrations.AddField(
            model_name='plantphoto',
            name='greenhouse_humidity',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plantphoto',
            name='greenhouse_illumination',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plantphoto',
            name='greenhouse_temprature',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plantphoto',
            name='plant_supply_K',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plantphoto',
            name='plant_supply_N',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plantphoto',
            name='plant_supply_P',
            field=models.TextField(blank=True),
        ),
    ]
