# Generated by Django 5.0.3 on 2024-04-07 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PredictionApp', '0013_remove_plantphoto_date_taken_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantphoto',
            old_name='plant_photo',
            new_name='ArchiveNote_photo',
        ),
    ]
