# Generated by Django 5.0.3 on 2024-04-07 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PredictionApp', '0014_rename_plant_photo_plantphoto_archivenote_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantphoto',
            old_name='ArchiveNote_photo',
            new_name='archiveNote',
        ),
    ]
