# Generated by Django 5.0.3 on 2024-04-15 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PredictionApp', '0016_alter_plantphoto_archivenote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AlterField(
            model_name='plantanalytics',
            name='plant_photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='PredictionApp.plantphoto'),
        ),
    ]
